'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace wsCuidadoPaliativo
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CuidadosPaleativosServiceImpServiceSoapBinding", [Namespace]:="http://www.colsanitas.com/CuidadosPaleativosService/")>  _
    Partial Public Class CuidadosPaleativosServiceImpService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private historicoRespuestasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private ultimasRespuestasOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.HistoriaClinica.MySettings.Default.HistoriaClinica_wsCuidadoPaliativo1_CuidadosPaleativosServiceImpService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event historicoRespuestasCompleted As historicoRespuestasCompletedEventHandler
        
        '''<remarks/>
        Public Event ultimasRespuestasCompleted As ultimasRespuestasCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.colsanitas.com/CuidadosPaleativosService/historicoRespuestas", RequestElementName:="HistoricoRespuestasRequest", RequestNamespace:="http://www.colsanitas.com/cuidadosPaleativos/xsd/schemas", ResponseElementName:="HistoricoRespuestasResponse", ResponseNamespace:="http://www.colsanitas.com/cuidadosPaleativos/xsd/schemas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function historicoRespuestas(ByVal parametrosPreguntas As UltimaRespuestaResquestType, ByVal rango As Integer, ByVal fecha As String, ByVal programa As String, ByVal seccion As String, ByVal subseccion As String, <System.Xml.Serialization.XmlArrayItemAttribute("grupoFecha", IsNullable:=false)> ByRef listadoRespuestas() As GrupoFechaType) As <System.Xml.Serialization.XmlElementAttribute("origenInfo")> String
            Dim results() As Object = Me.Invoke("historicoRespuestas", New Object() {parametrosPreguntas, rango, fecha, programa, seccion, subseccion})
            listadoRespuestas = CType(results(1),GrupoFechaType())
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub historicoRespuestasAsync(ByVal parametrosPreguntas As UltimaRespuestaResquestType, ByVal rango As Integer, ByVal fecha As String, ByVal programa As String, ByVal seccion As String, ByVal subseccion As String)
            Me.historicoRespuestasAsync(parametrosPreguntas, rango, fecha, programa, seccion, subseccion, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub historicoRespuestasAsync(ByVal parametrosPreguntas As UltimaRespuestaResquestType, ByVal rango As Integer, ByVal fecha As String, ByVal programa As String, ByVal seccion As String, ByVal subseccion As String, ByVal userState As Object)
            If (Me.historicoRespuestasOperationCompleted Is Nothing) Then
                Me.historicoRespuestasOperationCompleted = AddressOf Me.OnhistoricoRespuestasOperationCompleted
            End If
            Me.InvokeAsync("historicoRespuestas", New Object() {parametrosPreguntas, rango, fecha, programa, seccion, subseccion}, Me.historicoRespuestasOperationCompleted, userState)
        End Sub
        
        Private Sub OnhistoricoRespuestasOperationCompleted(ByVal arg As Object)
            If (Not (Me.historicoRespuestasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent historicoRespuestasCompleted(Me, New historicoRespuestasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.colsanitas.com/CuidadosPaleativosService/ultimasRespuestas", RequestElementName:="UltimasRespuestasRequest", RequestNamespace:="http://www.colsanitas.com/cuidadosPaleativos/xsd/schemas", ResponseElementName:="UltimasRespuestasResponse", ResponseNamespace:="http://www.colsanitas.com/cuidadosPaleativos/xsd/schemas", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ultimasRespuestas(ByVal tipoDocumento As String, ByVal numeroDocumento As String, <System.Xml.Serialization.XmlArrayItemAttribute("idPregunta", IsNullable:=false)> ByVal preguntas() As Long, ByVal origen As String, ByVal regional As String, <System.Xml.Serialization.XmlArrayItemAttribute("pregunta", IsNullable:=false)> ByRef resultados() As PreguntaType) As <System.Xml.Serialization.XmlElementAttribute("codigoError")> String
            Dim results() As Object = Me.Invoke("ultimasRespuestas", New Object() {tipoDocumento, numeroDocumento, preguntas, origen, regional})
            resultados = CType(results(1),PreguntaType())
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ultimasRespuestasAsync(ByVal tipoDocumento As String, ByVal numeroDocumento As String, ByVal preguntas() As Long, ByVal origen As String, ByVal regional As String)
            Me.ultimasRespuestasAsync(tipoDocumento, numeroDocumento, preguntas, origen, regional, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ultimasRespuestasAsync(ByVal tipoDocumento As String, ByVal numeroDocumento As String, ByVal preguntas() As Long, ByVal origen As String, ByVal regional As String, ByVal userState As Object)
            If (Me.ultimasRespuestasOperationCompleted Is Nothing) Then
                Me.ultimasRespuestasOperationCompleted = AddressOf Me.OnultimasRespuestasOperationCompleted
            End If
            Me.InvokeAsync("ultimasRespuestas", New Object() {tipoDocumento, numeroDocumento, preguntas, origen, regional}, Me.ultimasRespuestasOperationCompleted, userState)
        End Sub
        
        Private Sub OnultimasRespuestasOperationCompleted(ByVal arg As Object)
            If (Not (Me.ultimasRespuestasCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ultimasRespuestasCompleted(Me, New ultimasRespuestasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.colsanitas.com/cuidadosPaleativos/xsd/schemas")>  _
    Partial Public Class UltimaRespuestaResquestType
        
        Private tipoDocumentoField As String
        
        Private numeroDocumentoField As String
        
        Private preguntasField() As Long
        
        Private origenField As String
        
        Private regionalField As String
        
        '''<comentarios/>
        Public Property tipoDocumento() As String
            Get
                Return Me.tipoDocumentoField
            End Get
            Set
                Me.tipoDocumentoField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property numeroDocumento() As String
            Get
                Return Me.numeroDocumentoField
            End Get
            Set
                Me.numeroDocumentoField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute("idPregunta", IsNullable:=false)>  _
        Public Property preguntas() As Long()
            Get
                Return Me.preguntasField
            End Get
            Set
                Me.preguntasField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property origen() As String
            Get
                Return Me.origenField
            End Get
            Set
                Me.origenField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property regional() As String
            Get
                Return Me.regionalField
            End Get
            Set
                Me.regionalField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.colsanitas.com/cuidadosPaleativos/xsd/schemas")>  _
    Partial Public Class RespuestaCompuestaType
        
        Private idRespuestaField As String
        
        Private textoRespuestaField As String
        
        '''<comentarios/>
        Public Property idRespuesta() As String
            Get
                Return Me.idRespuestaField
            End Get
            Set
                Me.idRespuestaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property textoRespuesta() As String
            Get
                Return Me.textoRespuestaField
            End Get
            Set
                Me.textoRespuestaField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.colsanitas.com/cuidadosPaleativos/xsd/schemas")>  _
    Partial Public Class RespuestasType
        
        Private textoRespuestaField As String
        
        Private respuestaCompuestaField As RespuestaCompuestaType
        
        Private listadoIdRespuestaField() As String
        
        '''<comentarios/>
        Public Property textoRespuesta() As String
            Get
                Return Me.textoRespuestaField
            End Get
            Set
                Me.textoRespuestaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property respuestaCompuesta() As RespuestaCompuestaType
            Get
                Return Me.respuestaCompuestaField
            End Get
            Set
                Me.respuestaCompuestaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute("idRespuesta", IsNullable:=false)>  _
        Public Property listadoIdRespuesta() As String()
            Get
                Return Me.listadoIdRespuestaField
            End Get
            Set
                Me.listadoIdRespuestaField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.colsanitas.com/cuidadosPaleativos/xsd/schemas")>  _
    Partial Public Class PreguntaType
        
        Private idPreguntaField As String
        
        Private respuestasField As RespuestasType
        
        '''<comentarios/>
        Public Property idPregunta() As String
            Get
                Return Me.idPreguntaField
            End Get
            Set
                Me.idPreguntaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property respuestas() As RespuestasType
            Get
                Return Me.respuestasField
            End Get
            Set
                Me.respuestasField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.colsanitas.com/cuidadosPaleativos/xsd/schemas")>  _
    Partial Public Class RespuestaHistType
        
        Private idPreguntaField As String
        
        Private interpretacionField As String
        
        Private puntajeField As String
        
        Private codRespuestaField As String
        
        Private tipoRespuestaField As String
        
        '''<comentarios/>
        Public Property idPregunta() As String
            Get
                Return Me.idPreguntaField
            End Get
            Set
                Me.idPreguntaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property interpretacion() As String
            Get
                Return Me.interpretacionField
            End Get
            Set
                Me.interpretacionField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property puntaje() As String
            Get
                Return Me.puntajeField
            End Get
            Set
                Me.puntajeField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property codRespuesta() As String
            Get
                Return Me.codRespuestaField
            End Get
            Set
                Me.codRespuestaField = value
            End Set
        End Property
        
        '''<comentarios/>
        Public Property tipoRespuesta() As String
            Get
                Return Me.tipoRespuestaField
            End Get
            Set
                Me.tipoRespuestaField = value
            End Set
        End Property
    End Class
    
    '''<comentarios/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1099.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.colsanitas.com/cuidadosPaleativos/xsd/schemas")>  _
    Partial Public Class GrupoFechaType
        
        Private fechaField As String
        
        Private resultadosHistField() As RespuestaHistType
        
        '''<comentarios/>
        Public Property fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<comentarios/>
        <System.Xml.Serialization.XmlArrayItemAttribute("respuesta", IsNullable:=false)>  _
        Public Property resultadosHist() As RespuestaHistType()
            Get
                Return Me.resultadosHistField
            End Get
            Set
                Me.resultadosHistField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")>  _
    Public Delegate Sub historicoRespuestasCompletedEventHandler(ByVal sender As Object, ByVal e As historicoRespuestasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class historicoRespuestasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property listadoRespuestas() As GrupoFechaType()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),GrupoFechaType())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")>  _
    Public Delegate Sub ultimasRespuestasCompletedEventHandler(ByVal sender As Object, ByVal e As ultimasRespuestasCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ultimasRespuestasCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
        
        '''<remarks/>
        Public ReadOnly Property resultados() As PreguntaType()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(1),PreguntaType())
            End Get
        End Property
    End Class
End Namespace
