'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace wcfServiceResultadoLaboratorio
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://consultaavicena", ConfigurationName:="wcfServiceResultadoLaboratorio.WebServiceSoap")>  _
    Public Interface WebServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://consultaavicena/fncGetURLPDF", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function fncGetURLPDF(ByVal FechaPeticion As String, ByVal NumeroPeticion As String, ByVal Modulo As String) As wcfServiceResultadoLaboratorio.RutaPDF
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://consultaavicena/fncGetURLPDF", ReplyAction:="*")>  _
        Function fncGetURLPDFAsync(ByVal FechaPeticion As String, ByVal NumeroPeticion As String, ByVal Modulo As String) As System.Threading.Tasks.Task(Of wcfServiceResultadoLaboratorio.RutaPDF)
        
        'CODEGEN: Generating message contract since message fncGetSolicitudesByPacienteByFechasRequest has headers
        <System.ServiceModel.OperationContractAttribute(Action:="http://consultaavicena/fncGetSolicitudesByPacienteByFechas", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function fncGetSolicitudesByPacienteByFechas(ByVal request As wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasRequest) As wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://consultaavicena/fncGetSolicitudesByPacienteByFechas", ReplyAction:="*")>  _
        Function fncGetSolicitudesByPacienteByFechasAsync(ByVal request As wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasRequest) As System.Threading.Tasks.Task(Of wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://consultaavicena")>  _
    Partial Public Class RutaPDF
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private uRL_PDFField As String
        
        Private strErrorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property URL_PDF() As String
            Get
                Return Me.uRL_PDFField
            End Get
            Set
                Me.uRL_PDFField = value
                Me.RaisePropertyChanged("URL_PDF")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property strError() As String
            Get
                Return Me.strErrorField
            End Get
            Set
                Me.strErrorField = value
                Me.RaisePropertyChanged("strError")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://consultaavicena")>  _
    Partial Public Class Peticion
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private numeroPeticionField As String
        
        Private fechaPeticionField As String
        
        Private estadoPeticionField As String
        
        Private moduloField As String
        
        Private descripcionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property NumeroPeticion() As String
            Get
                Return Me.numeroPeticionField
            End Get
            Set
                Me.numeroPeticionField = value
                Me.RaisePropertyChanged("NumeroPeticion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property FechaPeticion() As String
            Get
                Return Me.fechaPeticionField
            End Get
            Set
                Me.fechaPeticionField = value
                Me.RaisePropertyChanged("FechaPeticion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property EstadoPeticion() As String
            Get
                Return Me.estadoPeticionField
            End Get
            Set
                Me.estadoPeticionField = value
                Me.RaisePropertyChanged("EstadoPeticion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property Modulo() As String
            Get
                Return Me.moduloField
            End Get
            Set
                Me.moduloField = value
                Me.RaisePropertyChanged("Modulo")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
                Me.RaisePropertyChanged("Descripcion")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://consultaavicena")>  _
    Partial Public Class Paciente
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private tipoIdentificacionField As String
        
        Private numeroIdentificacionField As String
        
        Private nombrePacienteField As String
        
        Private peticionesField() As Peticion
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property TipoIdentificacion() As String
            Get
                Return Me.tipoIdentificacionField
            End Get
            Set
                Me.tipoIdentificacionField = value
                Me.RaisePropertyChanged("TipoIdentificacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property NumeroIdentificacion() As String
            Get
                Return Me.numeroIdentificacionField
            End Get
            Set
                Me.numeroIdentificacionField = value
                Me.RaisePropertyChanged("NumeroIdentificacion")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property NombrePaciente() As String
            Get
                Return Me.nombrePacienteField
            End Get
            Set
                Me.nombrePacienteField = value
                Me.RaisePropertyChanged("NombrePaciente")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayAttribute(Order:=3)>  _
        Public Property Peticiones() As Peticion()
            Get
                Return Me.peticionesField
            End Get
            Set
                Me.peticionesField = value
                Me.RaisePropertyChanged("Peticiones")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://consultaavicena")>  _
    Partial Public Class Consulta
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private estadoFinalField As Short
        
        Private pacienteField As Paciente
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property EstadoFinal() As Short
            Get
                Return Me.estadoFinalField
            End Get
            Set
                Me.estadoFinalField = value
                Me.RaisePropertyChanged("EstadoFinal")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property Paciente() As Paciente
            Get
                Return Me.pacienteField
            End Get
            Set
                Me.pacienteField = value
                Me.RaisePropertyChanged("Paciente")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fncGetSolicitudesByPacienteByFechas", WrapperNamespace:="http://consultaavicena", IsWrapped:=true)>  _
    Partial Public Class fncGetSolicitudesByPacienteByFechasRequest
        
        <System.ServiceModel.MessageHeaderAttribute([Namespace]:="http://consultaavicena")>  _
        Public Consulta As wcfServiceResultadoLaboratorio.Consulta
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://consultaavicena", Order:=0)>  _
        Public TipoIdentificacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://consultaavicena", Order:=1)>  _
        Public Identificacion As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://consultaavicena", Order:=2)>  _
        Public FechaInicial As String
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://consultaavicena", Order:=3)>  _
        Public FechaFinal As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Consulta As wcfServiceResultadoLaboratorio.Consulta, ByVal TipoIdentificacion As String, ByVal Identificacion As String, ByVal FechaInicial As String, ByVal FechaFinal As String)
            MyBase.New
            Me.Consulta = Consulta
            Me.TipoIdentificacion = TipoIdentificacion
            Me.Identificacion = Identificacion
            Me.FechaInicial = FechaInicial
            Me.FechaFinal = FechaFinal
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(WrapperName:="fncGetSolicitudesByPacienteByFechasResponse", WrapperNamespace:="http://consultaavicena", IsWrapped:=true)>  _
    Partial Public Class fncGetSolicitudesByPacienteByFechasResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://consultaavicena", Order:=0)>  _
        Public fncGetSolicitudesByPacienteByFechasResult() As wcfServiceResultadoLaboratorio.Consulta
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal fncGetSolicitudesByPacienteByFechasResult() As wcfServiceResultadoLaboratorio.Consulta)
            MyBase.New
            Me.fncGetSolicitudesByPacienteByFechasResult = fncGetSolicitudesByPacienteByFechasResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebServiceSoapChannel
        Inherits wcfServiceResultadoLaboratorio.WebServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of wcfServiceResultadoLaboratorio.WebServiceSoap)
        Implements wcfServiceResultadoLaboratorio.WebServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function fncGetURLPDF(ByVal FechaPeticion As String, ByVal NumeroPeticion As String, ByVal Modulo As String) As wcfServiceResultadoLaboratorio.RutaPDF Implements wcfServiceResultadoLaboratorio.WebServiceSoap.fncGetURLPDF
            Return MyBase.Channel.fncGetURLPDF(FechaPeticion, NumeroPeticion, Modulo)
        End Function
        
        Public Function fncGetURLPDFAsync(ByVal FechaPeticion As String, ByVal NumeroPeticion As String, ByVal Modulo As String) As System.Threading.Tasks.Task(Of wcfServiceResultadoLaboratorio.RutaPDF) Implements wcfServiceResultadoLaboratorio.WebServiceSoap.fncGetURLPDFAsync
            Return MyBase.Channel.fncGetURLPDFAsync(FechaPeticion, NumeroPeticion, Modulo)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wcfServiceResultadoLaboratorio_WebServiceSoap_fncGetSolicitudesByPacienteByFechas(ByVal request As wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasRequest) As wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasResponse Implements wcfServiceResultadoLaboratorio.WebServiceSoap.fncGetSolicitudesByPacienteByFechas
            Return MyBase.Channel.fncGetSolicitudesByPacienteByFechas(request)
        End Function
        
        Public Function fncGetSolicitudesByPacienteByFechas(ByVal Consulta As wcfServiceResultadoLaboratorio.Consulta, ByVal TipoIdentificacion As String, ByVal Identificacion As String, ByVal FechaInicial As String, ByVal FechaFinal As String) As wcfServiceResultadoLaboratorio.Consulta()
            Dim inValue As wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasRequest = New wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasRequest()
            inValue.Consulta = Consulta
            inValue.TipoIdentificacion = TipoIdentificacion
            inValue.Identificacion = Identificacion
            inValue.FechaInicial = FechaInicial
            inValue.FechaFinal = FechaFinal
            Dim retVal As wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasResponse = CType(Me,wcfServiceResultadoLaboratorio.WebServiceSoap).fncGetSolicitudesByPacienteByFechas(inValue)
            Return retVal.fncGetSolicitudesByPacienteByFechasResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function wcfServiceResultadoLaboratorio_WebServiceSoap_fncGetSolicitudesByPacienteByFechasAsync(ByVal request As wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasRequest) As System.Threading.Tasks.Task(Of wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasResponse) Implements wcfServiceResultadoLaboratorio.WebServiceSoap.fncGetSolicitudesByPacienteByFechasAsync
            Return MyBase.Channel.fncGetSolicitudesByPacienteByFechasAsync(request)
        End Function
        
        Public Function fncGetSolicitudesByPacienteByFechasAsync(ByVal Consulta As wcfServiceResultadoLaboratorio.Consulta, ByVal TipoIdentificacion As String, ByVal Identificacion As String, ByVal FechaInicial As String, ByVal FechaFinal As String) As System.Threading.Tasks.Task(Of wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasResponse)
            Dim inValue As wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasRequest = New wcfServiceResultadoLaboratorio.fncGetSolicitudesByPacienteByFechasRequest()
            inValue.Consulta = Consulta
            inValue.TipoIdentificacion = TipoIdentificacion
            inValue.Identificacion = Identificacion
            inValue.FechaInicial = FechaInicial
            inValue.FechaFinal = FechaFinal
            Return CType(Me,wcfServiceResultadoLaboratorio.WebServiceSoap).fncGetSolicitudesByPacienteByFechasAsync(inValue)
        End Function
    End Class
End Namespace
