name: HC Medica .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  specific-sdk-version-17763:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@main
        with:
          sdk-version: 17763
  setup-version:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        #operating-system: [windows-latest]
        dotnet-version: ['4.5.0', '4.5.1', '4.5.2', '4.5.3', '4.5.4', '4.5.5', '4.5.6']
        #dotnet-version: ['4.5.x']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        #uses: ./
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
     # - name: Check installed version
     #   shell: pwsh
     #   run: |
     #     $version = & dotnet --version
     #     Write-Host "Installed version: $version"
     #     if (-not $version.StartsWith("${{ matrix.dotnet-version }}")) { throw "Unexpected version" }
