name: HC Medica .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4.5
      with:
        dotnet-version: 4.5
          
    #- name: Setup .NET Core SDK
     # uses: actions/setup-dotnet@v3.0.3
      #with:
       # dotnet-version: 4.5
      
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.0.2
     
    - name: Build
      #run: find -name HistoriaClinica.sln
      #run: msbuild hcmedica\HistoriaClinica.sln #/p:Configuration=release
      run: msbuild HistoriaClinica.sln -p:Configuration=Release
